/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.calcul.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CalculUiModule extends AbstractCalculUiModule {

	public CalculUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
