/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.airport.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAirPortScopeProvider extends DelegatingScopeProvider {
}
