/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.ipsl.mydsl.MonDslRuntimeModule;
import org.xtext.ipsl.mydsl.MonDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MonDslIdeSetup extends MonDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MonDslRuntimeModule(), new MonDslIdeModule()));
	}
	
}
