/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mondsl1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mondsl1.ui.internal.Mondsl1Activator;

public class MyDsl1UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Mondsl1Activator.getInstance().getInjector("org.xtext.example.mondsl1.MyDsl1");
	}

}
