/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.airport.airPort.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ipsl.airport.airPort.AirPortPackage;
import org.xtext.ipsl.airport.airPort.Avion;
import org.xtext.ipsl.airport.airPort.Moteurs;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Avion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ipsl.airport.airPort.impl.AvionImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.ipsl.airport.airPort.impl.AvionImpl#getPassagers <em>Passagers</em>}</li>
 *   <li>{@link org.xtext.ipsl.airport.airPort.impl.AvionImpl#getMotorisation <em>Motorisation</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AvionImpl extends MinimalEObjectImpl.Container implements Avion
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPassagers() <em>Passagers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPassagers()
   * @generated
   * @ordered
   */
  protected static final int PASSAGERS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPassagers() <em>Passagers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPassagers()
   * @generated
   * @ordered
   */
  protected int passagers = PASSAGERS_EDEFAULT;

  /**
   * The default value of the '{@link #getMotorisation() <em>Motorisation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMotorisation()
   * @generated
   * @ordered
   */
  protected static final Moteurs MOTORISATION_EDEFAULT = Moteurs.P1;

  /**
   * The cached value of the '{@link #getMotorisation() <em>Motorisation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMotorisation()
   * @generated
   * @ordered
   */
  protected Moteurs motorisation = MOTORISATION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AvionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AirPortPackage.Literals.AVION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPortPackage.AVION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPassagers()
  {
    return passagers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPassagers(int newPassagers)
  {
    int oldPassagers = passagers;
    passagers = newPassagers;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPortPackage.AVION__PASSAGERS, oldPassagers, passagers));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Moteurs getMotorisation()
  {
    return motorisation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMotorisation(Moteurs newMotorisation)
  {
    Moteurs oldMotorisation = motorisation;
    motorisation = newMotorisation == null ? MOTORISATION_EDEFAULT : newMotorisation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AirPortPackage.AVION__MOTORISATION, oldMotorisation, motorisation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AirPortPackage.AVION__NAME:
        return getName();
      case AirPortPackage.AVION__PASSAGERS:
        return getPassagers();
      case AirPortPackage.AVION__MOTORISATION:
        return getMotorisation();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AirPortPackage.AVION__NAME:
        setName((String)newValue);
        return;
      case AirPortPackage.AVION__PASSAGERS:
        setPassagers((Integer)newValue);
        return;
      case AirPortPackage.AVION__MOTORISATION:
        setMotorisation((Moteurs)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AirPortPackage.AVION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AirPortPackage.AVION__PASSAGERS:
        setPassagers(PASSAGERS_EDEFAULT);
        return;
      case AirPortPackage.AVION__MOTORISATION:
        setMotorisation(MOTORISATION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AirPortPackage.AVION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AirPortPackage.AVION__PASSAGERS:
        return passagers != PASSAGERS_EDEFAULT;
      case AirPortPackage.AVION__MOTORISATION:
        return motorisation != MOTORISATION_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", passagers: ");
    result.append(passagers);
    result.append(", motorisation: ");
    result.append(motorisation);
    result.append(')');
    return result.toString();
  }

} //AvionImpl
