/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mondsl1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyDsl1UiModule extends AbstractMyDsl1UiModule {

	public MyDsl1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
