/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.mydsl.monDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ipsl.mydsl.monDsl.MonDslPackage#getElementType()
 * @model
 * @generated
 */
public interface ElementType extends EObject
{
} // ElementType
