/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.airport.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AirPortAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/ipsl/airport/parser/antlr/internal/InternalAirPort.tokens");
	}
}
