/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.calcul;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CalculStandaloneSetup extends CalculStandaloneSetupGenerated {

	public static void doSetup() {
		new CalculStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
