/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.ipsl.figure.ui.internal.FigureActivator;

public class FigureUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FigureActivator.getInstance().getInjector("org.xtext.ipsl.figure.Figure");
	}

}
