<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="enseignement" nsURI="www.enseignement.sn" nsPrefix="enseignement">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cours" upperBound="-1"
        eType="#//Cours" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="etudiants" upperBound="-1"
        eType="#//Etudiant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultats" upperBound="-1"
        eType="#//Resultat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="universites" upperBound="-1"
        eType="#//Universite" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="professeurs" upperBound="-1"
        eType="#//Professeur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Etudiant">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="q1"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="q1" value="notes->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codePerm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1"
        eType="#//Resultat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resultat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="session" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultats" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cours" lowerBound="1" eType="#//Cours"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cours">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sigle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Professeur">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employeur" lowerBound="1"
        eType="#//Universite" eOpposite="#//Universite/employes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Universite">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="q2 q3 q4"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="q2" value="employes->select(age > 40)->notEmpty()"/>
      <details key="q3" value="employes->select(p:Professeur | p.age  > 40)->notEmpty()"/>
      <details key="q4" value="employes->reject(age &lt; 40)->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employes" upperBound="-1"
        eType="#//Professeur" containment="true" eOpposite="#//Professeur/employeur"/>
  </eClassifiers>
</ecore:EPackage>
