/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure.figure.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ipsl.figure.figure.CERCLE;
import org.xtext.ipsl.figure.figure.FigurePackage;
import org.xtext.ipsl.figure.figure.REEL;
import org.xtext.ipsl.figure.figure.RETURN;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>CERCLE</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.CERCLEImpl#getNom <em>Nom</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.CERCLEImpl#getDebut <em>Debut</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.CERCLEImpl#getRayon <em>Rayon</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.CERCLEImpl#getRetour <em>Retour</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.CERCLEImpl#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CERCLEImpl extends MinimalEObjectImpl.Container implements CERCLE
{
  /**
   * The default value of the '{@link #getNom() <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom()
   * @generated
   * @ordered
   */
  protected static final String NOM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNom() <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom()
   * @generated
   * @ordered
   */
  protected String nom = NOM_EDEFAULT;

  /**
   * The default value of the '{@link #getDebut() <em>Debut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDebut()
   * @generated
   * @ordered
   */
  protected static final String DEBUT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDebut() <em>Debut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDebut()
   * @generated
   * @ordered
   */
  protected String debut = DEBUT_EDEFAULT;

  /**
   * The cached value of the '{@link #getRayon() <em>Rayon</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRayon()
   * @generated
   * @ordered
   */
  protected REEL rayon;

  /**
   * The cached value of the '{@link #getRetour() <em>Retour</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRetour()
   * @generated
   * @ordered
   */
  protected RETURN retour;

  /**
   * The default value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected static final String END_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected String end = END_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CERCLEImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FigurePackage.Literals.CERCLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNom()
  {
    return nom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNom(String newNom)
  {
    String oldNom = nom;
    nom = newNom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.CERCLE__NOM, oldNom, nom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDebut()
  {
    return debut;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDebut(String newDebut)
  {
    String oldDebut = debut;
    debut = newDebut;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.CERCLE__DEBUT, oldDebut, debut));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public REEL getRayon()
  {
    return rayon;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRayon(REEL newRayon, NotificationChain msgs)
  {
    REEL oldRayon = rayon;
    rayon = newRayon;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FigurePackage.CERCLE__RAYON, oldRayon, newRayon);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRayon(REEL newRayon)
  {
    if (newRayon != rayon)
    {
      NotificationChain msgs = null;
      if (rayon != null)
        msgs = ((InternalEObject)rayon).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FigurePackage.CERCLE__RAYON, null, msgs);
      if (newRayon != null)
        msgs = ((InternalEObject)newRayon).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FigurePackage.CERCLE__RAYON, null, msgs);
      msgs = basicSetRayon(newRayon, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.CERCLE__RAYON, newRayon, newRayon));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RETURN getRetour()
  {
    return retour;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRetour(RETURN newRetour, NotificationChain msgs)
  {
    RETURN oldRetour = retour;
    retour = newRetour;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FigurePackage.CERCLE__RETOUR, oldRetour, newRetour);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRetour(RETURN newRetour)
  {
    if (newRetour != retour)
    {
      NotificationChain msgs = null;
      if (retour != null)
        msgs = ((InternalEObject)retour).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FigurePackage.CERCLE__RETOUR, null, msgs);
      if (newRetour != null)
        msgs = ((InternalEObject)newRetour).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FigurePackage.CERCLE__RETOUR, null, msgs);
      msgs = basicSetRetour(newRetour, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.CERCLE__RETOUR, newRetour, newRetour));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEnd()
  {
    return end;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnd(String newEnd)
  {
    String oldEnd = end;
    end = newEnd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.CERCLE__END, oldEnd, end));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FigurePackage.CERCLE__RAYON:
        return basicSetRayon(null, msgs);
      case FigurePackage.CERCLE__RETOUR:
        return basicSetRetour(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FigurePackage.CERCLE__NOM:
        return getNom();
      case FigurePackage.CERCLE__DEBUT:
        return getDebut();
      case FigurePackage.CERCLE__RAYON:
        return getRayon();
      case FigurePackage.CERCLE__RETOUR:
        return getRetour();
      case FigurePackage.CERCLE__END:
        return getEnd();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FigurePackage.CERCLE__NOM:
        setNom((String)newValue);
        return;
      case FigurePackage.CERCLE__DEBUT:
        setDebut((String)newValue);
        return;
      case FigurePackage.CERCLE__RAYON:
        setRayon((REEL)newValue);
        return;
      case FigurePackage.CERCLE__RETOUR:
        setRetour((RETURN)newValue);
        return;
      case FigurePackage.CERCLE__END:
        setEnd((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FigurePackage.CERCLE__NOM:
        setNom(NOM_EDEFAULT);
        return;
      case FigurePackage.CERCLE__DEBUT:
        setDebut(DEBUT_EDEFAULT);
        return;
      case FigurePackage.CERCLE__RAYON:
        setRayon((REEL)null);
        return;
      case FigurePackage.CERCLE__RETOUR:
        setRetour((RETURN)null);
        return;
      case FigurePackage.CERCLE__END:
        setEnd(END_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FigurePackage.CERCLE__NOM:
        return NOM_EDEFAULT == null ? nom != null : !NOM_EDEFAULT.equals(nom);
      case FigurePackage.CERCLE__DEBUT:
        return DEBUT_EDEFAULT == null ? debut != null : !DEBUT_EDEFAULT.equals(debut);
      case FigurePackage.CERCLE__RAYON:
        return rayon != null;
      case FigurePackage.CERCLE__RETOUR:
        return retour != null;
      case FigurePackage.CERCLE__END:
        return END_EDEFAULT == null ? end != null : !END_EDEFAULT.equals(end);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nom: ");
    result.append(nom);
    result.append(", debut: ");
    result.append(debut);
    result.append(", end: ");
    result.append(end);
    result.append(')');
    return result.toString();
  }

} //CERCLEImpl
