/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure.figure.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ipsl.figure.figure.FIGURE;
import org.xtext.ipsl.figure.figure.FigurePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>FIGURE</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.FIGUREImpl#getNom <em>Nom</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FIGUREImpl extends MinimalEObjectImpl.Container implements FIGURE
{
  /**
   * The cached value of the '{@link #getNom() <em>Nom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom()
   * @generated
   * @ordered
   */
  protected EObject nom;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FIGUREImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FigurePackage.Literals.FIGURE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject getNom()
  {
    return nom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNom(EObject newNom, NotificationChain msgs)
  {
    EObject oldNom = nom;
    nom = newNom;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FigurePackage.FIGURE__NOM, oldNom, newNom);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNom(EObject newNom)
  {
    if (newNom != nom)
    {
      NotificationChain msgs = null;
      if (nom != null)
        msgs = ((InternalEObject)nom).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FigurePackage.FIGURE__NOM, null, msgs);
      if (newNom != null)
        msgs = ((InternalEObject)newNom).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FigurePackage.FIGURE__NOM, null, msgs);
      msgs = basicSetNom(newNom, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.FIGURE__NOM, newNom, newNom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FigurePackage.FIGURE__NOM:
        return basicSetNom(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FigurePackage.FIGURE__NOM:
        return getNom();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FigurePackage.FIGURE__NOM:
        setNom((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FigurePackage.FIGURE__NOM:
        setNom((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FigurePackage.FIGURE__NOM:
        return nom != null;
    }
    return super.eIsSet(featureID);
  }

} //FIGUREImpl
