/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure.figure.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ipsl.figure.figure.FigurePackage;
import org.xtext.ipsl.figure.figure.RECTANGLE;
import org.xtext.ipsl.figure.figure.REEL;
import org.xtext.ipsl.figure.figure.RETURN;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>RECTANGLE</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.RECTANGLEImpl#getNom <em>Nom</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.RECTANGLEImpl#getDebut <em>Debut</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.RECTANGLEImpl#getLongueur <em>Longueur</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.RECTANGLEImpl#getLargeur <em>Largeur</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.RECTANGLEImpl#getRetour <em>Retour</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.impl.RECTANGLEImpl#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RECTANGLEImpl extends MinimalEObjectImpl.Container implements RECTANGLE
{
  /**
   * The default value of the '{@link #getNom() <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom()
   * @generated
   * @ordered
   */
  protected static final String NOM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNom() <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom()
   * @generated
   * @ordered
   */
  protected String nom = NOM_EDEFAULT;

  /**
   * The default value of the '{@link #getDebut() <em>Debut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDebut()
   * @generated
   * @ordered
   */
  protected static final String DEBUT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDebut() <em>Debut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDebut()
   * @generated
   * @ordered
   */
  protected String debut = DEBUT_EDEFAULT;

  /**
   * The cached value of the '{@link #getLongueur() <em>Longueur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLongueur()
   * @generated
   * @ordered
   */
  protected REEL longueur;

  /**
   * The cached value of the '{@link #getLargeur() <em>Largeur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLargeur()
   * @generated
   * @ordered
   */
  protected REEL largeur;

  /**
   * The cached value of the '{@link #getRetour() <em>Retour</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRetour()
   * @generated
   * @ordered
   */
  protected RETURN retour;

  /**
   * The default value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected static final String END_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected String end = END_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RECTANGLEImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FigurePackage.Literals.RECTANGLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNom()
  {
    return nom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNom(String newNom)
  {
    String oldNom = nom;
    nom = newNom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.RECTANGLE__NOM, oldNom, nom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDebut()
  {
    return debut;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDebut(String newDebut)
  {
    String oldDebut = debut;
    debut = newDebut;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.RECTANGLE__DEBUT, oldDebut, debut));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public REEL getLongueur()
  {
    return longueur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLongueur(REEL newLongueur, NotificationChain msgs)
  {
    REEL oldLongueur = longueur;
    longueur = newLongueur;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FigurePackage.RECTANGLE__LONGUEUR, oldLongueur, newLongueur);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLongueur(REEL newLongueur)
  {
    if (newLongueur != longueur)
    {
      NotificationChain msgs = null;
      if (longueur != null)
        msgs = ((InternalEObject)longueur).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FigurePackage.RECTANGLE__LONGUEUR, null, msgs);
      if (newLongueur != null)
        msgs = ((InternalEObject)newLongueur).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FigurePackage.RECTANGLE__LONGUEUR, null, msgs);
      msgs = basicSetLongueur(newLongueur, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.RECTANGLE__LONGUEUR, newLongueur, newLongueur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public REEL getLargeur()
  {
    return largeur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLargeur(REEL newLargeur, NotificationChain msgs)
  {
    REEL oldLargeur = largeur;
    largeur = newLargeur;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FigurePackage.RECTANGLE__LARGEUR, oldLargeur, newLargeur);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLargeur(REEL newLargeur)
  {
    if (newLargeur != largeur)
    {
      NotificationChain msgs = null;
      if (largeur != null)
        msgs = ((InternalEObject)largeur).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FigurePackage.RECTANGLE__LARGEUR, null, msgs);
      if (newLargeur != null)
        msgs = ((InternalEObject)newLargeur).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FigurePackage.RECTANGLE__LARGEUR, null, msgs);
      msgs = basicSetLargeur(newLargeur, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.RECTANGLE__LARGEUR, newLargeur, newLargeur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RETURN getRetour()
  {
    return retour;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRetour(RETURN newRetour, NotificationChain msgs)
  {
    RETURN oldRetour = retour;
    retour = newRetour;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FigurePackage.RECTANGLE__RETOUR, oldRetour, newRetour);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRetour(RETURN newRetour)
  {
    if (newRetour != retour)
    {
      NotificationChain msgs = null;
      if (retour != null)
        msgs = ((InternalEObject)retour).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FigurePackage.RECTANGLE__RETOUR, null, msgs);
      if (newRetour != null)
        msgs = ((InternalEObject)newRetour).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FigurePackage.RECTANGLE__RETOUR, null, msgs);
      msgs = basicSetRetour(newRetour, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.RECTANGLE__RETOUR, newRetour, newRetour));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEnd()
  {
    return end;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnd(String newEnd)
  {
    String oldEnd = end;
    end = newEnd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FigurePackage.RECTANGLE__END, oldEnd, end));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FigurePackage.RECTANGLE__LONGUEUR:
        return basicSetLongueur(null, msgs);
      case FigurePackage.RECTANGLE__LARGEUR:
        return basicSetLargeur(null, msgs);
      case FigurePackage.RECTANGLE__RETOUR:
        return basicSetRetour(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FigurePackage.RECTANGLE__NOM:
        return getNom();
      case FigurePackage.RECTANGLE__DEBUT:
        return getDebut();
      case FigurePackage.RECTANGLE__LONGUEUR:
        return getLongueur();
      case FigurePackage.RECTANGLE__LARGEUR:
        return getLargeur();
      case FigurePackage.RECTANGLE__RETOUR:
        return getRetour();
      case FigurePackage.RECTANGLE__END:
        return getEnd();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FigurePackage.RECTANGLE__NOM:
        setNom((String)newValue);
        return;
      case FigurePackage.RECTANGLE__DEBUT:
        setDebut((String)newValue);
        return;
      case FigurePackage.RECTANGLE__LONGUEUR:
        setLongueur((REEL)newValue);
        return;
      case FigurePackage.RECTANGLE__LARGEUR:
        setLargeur((REEL)newValue);
        return;
      case FigurePackage.RECTANGLE__RETOUR:
        setRetour((RETURN)newValue);
        return;
      case FigurePackage.RECTANGLE__END:
        setEnd((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FigurePackage.RECTANGLE__NOM:
        setNom(NOM_EDEFAULT);
        return;
      case FigurePackage.RECTANGLE__DEBUT:
        setDebut(DEBUT_EDEFAULT);
        return;
      case FigurePackage.RECTANGLE__LONGUEUR:
        setLongueur((REEL)null);
        return;
      case FigurePackage.RECTANGLE__LARGEUR:
        setLargeur((REEL)null);
        return;
      case FigurePackage.RECTANGLE__RETOUR:
        setRetour((RETURN)null);
        return;
      case FigurePackage.RECTANGLE__END:
        setEnd(END_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FigurePackage.RECTANGLE__NOM:
        return NOM_EDEFAULT == null ? nom != null : !NOM_EDEFAULT.equals(nom);
      case FigurePackage.RECTANGLE__DEBUT:
        return DEBUT_EDEFAULT == null ? debut != null : !DEBUT_EDEFAULT.equals(debut);
      case FigurePackage.RECTANGLE__LONGUEUR:
        return longueur != null;
      case FigurePackage.RECTANGLE__LARGEUR:
        return largeur != null;
      case FigurePackage.RECTANGLE__RETOUR:
        return retour != null;
      case FigurePackage.RECTANGLE__END:
        return END_EDEFAULT == null ? end != null : !END_EDEFAULT.equals(end);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nom: ");
    result.append(nom);
    result.append(", debut: ");
    result.append(debut);
    result.append(", end: ");
    result.append(end);
    result.append(')');
    return result.toString();
  }

} //RECTANGLEImpl
