/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MonDslStandaloneSetup extends MonDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MonDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
