/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.airport.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractAirPortValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.ipsl.airport.airPort.AirPortPackage.eINSTANCE);
		return result;
	}
}
