/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mondsl1;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyDsl1StandaloneSetup extends MyDsl1StandaloneSetupGenerated {

	public static void doSetup() {
		new MyDsl1StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
