/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMonDslScopeProvider extends DelegatingScopeProvider {
}
