/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mondsl1.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class MyDsl1ProposalProvider extends AbstractMyDsl1ProposalProvider {
}
