/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure.figure;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.ipsl.figure.figure.FigurePackage
 * @generated
 */
public interface FigureFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FigureFactory eINSTANCE = org.xtext.ipsl.figure.figure.impl.FigureFactoryImpl.init();

  /**
   * Returns a new object of class '<em>PROGRAMME</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PROGRAMME</em>'.
   * @generated
   */
  PROGRAMME createPROGRAMME();

  /**
   * Returns a new object of class '<em>FIGURE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FIGURE</em>'.
   * @generated
   */
  FIGURE createFIGURE();

  /**
   * Returns a new object of class '<em>CARRE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CARRE</em>'.
   * @generated
   */
  CARRE createCARRE();

  /**
   * Returns a new object of class '<em>RECTANGLE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RECTANGLE</em>'.
   * @generated
   */
  RECTANGLE createRECTANGLE();

  /**
   * Returns a new object of class '<em>CERCLE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CERCLE</em>'.
   * @generated
   */
  CERCLE createCERCLE();

  /**
   * Returns a new object of class '<em>RETURN</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RETURN</em>'.
   * @generated
   */
  RETURN createRETURN();

  /**
   * Returns a new object of class '<em>REEL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>REEL</em>'.
   * @generated
   */
  REEL createREEL();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  FigurePackage getFigurePackage();

} //FigureFactory
