/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure.figure;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.ipsl.figure.figure.FigureFactory
 * @model kind="package"
 * @generated
 */
public interface FigurePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "figure";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/ipsl/figure/Figure";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "figure";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FigurePackage eINSTANCE = org.xtext.ipsl.figure.figure.impl.FigurePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.ipsl.figure.figure.impl.PROGRAMMEImpl <em>PROGRAMME</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.figure.figure.impl.PROGRAMMEImpl
   * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getPROGRAMME()
   * @generated
   */
  int PROGRAMME = 0;

  /**
   * The feature id for the '<em><b>Fig</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMME__FIG = 0;

  /**
   * The number of structural features of the '<em>PROGRAMME</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ipsl.figure.figure.impl.FIGUREImpl <em>FIGURE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.figure.figure.impl.FIGUREImpl
   * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getFIGURE()
   * @generated
   */
  int FIGURE = 1;

  /**
   * The feature id for the '<em><b>Nom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIGURE__NOM = 0;

  /**
   * The number of structural features of the '<em>FIGURE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIGURE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ipsl.figure.figure.impl.CARREImpl <em>CARRE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.figure.figure.impl.CARREImpl
   * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getCARRE()
   * @generated
   */
  int CARRE = 2;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARRE__NOM = 0;

  /**
   * The feature id for the '<em><b>Debut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARRE__DEBUT = 1;

  /**
   * The feature id for the '<em><b>Cote</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARRE__COTE = 2;

  /**
   * The feature id for the '<em><b>Retour</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARRE__RETOUR = 3;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARRE__END = 4;

  /**
   * The number of structural features of the '<em>CARRE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARRE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.ipsl.figure.figure.impl.RECTANGLEImpl <em>RECTANGLE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.figure.figure.impl.RECTANGLEImpl
   * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getRECTANGLE()
   * @generated
   */
  int RECTANGLE = 3;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGLE__NOM = 0;

  /**
   * The feature id for the '<em><b>Debut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGLE__DEBUT = 1;

  /**
   * The feature id for the '<em><b>Longueur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGLE__LONGUEUR = 2;

  /**
   * The feature id for the '<em><b>Largeur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGLE__LARGEUR = 3;

  /**
   * The feature id for the '<em><b>Retour</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGLE__RETOUR = 4;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGLE__END = 5;

  /**
   * The number of structural features of the '<em>RECTANGLE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGLE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.ipsl.figure.figure.impl.CERCLEImpl <em>CERCLE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.figure.figure.impl.CERCLEImpl
   * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getCERCLE()
   * @generated
   */
  int CERCLE = 4;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CERCLE__NOM = 0;

  /**
   * The feature id for the '<em><b>Debut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CERCLE__DEBUT = 1;

  /**
   * The feature id for the '<em><b>Rayon</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CERCLE__RAYON = 2;

  /**
   * The feature id for the '<em><b>Retour</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CERCLE__RETOUR = 3;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CERCLE__END = 4;

  /**
   * The number of structural features of the '<em>CERCLE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CERCLE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.ipsl.figure.figure.impl.RETURNImpl <em>RETURN</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.figure.figure.impl.RETURNImpl
   * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getRETURN()
   * @generated
   */
  int RETURN = 5;

  /**
   * The feature id for the '<em><b>Resultat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN__RESULTAT = 0;

  /**
   * The number of structural features of the '<em>RETURN</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ipsl.figure.figure.impl.REELImpl <em>REEL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.figure.figure.impl.REELImpl
   * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getREEL()
   * @generated
   */
  int REEL = 6;

  /**
   * The feature id for the '<em><b>Reel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REEL__REEL = 0;

  /**
   * The number of structural features of the '<em>REEL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REEL_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.figure.figure.PROGRAMME <em>PROGRAMME</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PROGRAMME</em>'.
   * @see org.xtext.ipsl.figure.figure.PROGRAMME
   * @generated
   */
  EClass getPROGRAMME();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.figure.figure.PROGRAMME#getFig <em>Fig</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fig</em>'.
   * @see org.xtext.ipsl.figure.figure.PROGRAMME#getFig()
   * @see #getPROGRAMME()
   * @generated
   */
  EReference getPROGRAMME_Fig();

  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.figure.figure.FIGURE <em>FIGURE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FIGURE</em>'.
   * @see org.xtext.ipsl.figure.figure.FIGURE
   * @generated
   */
  EClass getFIGURE();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.figure.figure.FIGURE#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nom</em>'.
   * @see org.xtext.ipsl.figure.figure.FIGURE#getNom()
   * @see #getFIGURE()
   * @generated
   */
  EReference getFIGURE_Nom();

  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.figure.figure.CARRE <em>CARRE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CARRE</em>'.
   * @see org.xtext.ipsl.figure.figure.CARRE
   * @generated
   */
  EClass getCARRE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.CARRE#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see org.xtext.ipsl.figure.figure.CARRE#getNom()
   * @see #getCARRE()
   * @generated
   */
  EAttribute getCARRE_Nom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.CARRE#getDebut <em>Debut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Debut</em>'.
   * @see org.xtext.ipsl.figure.figure.CARRE#getDebut()
   * @see #getCARRE()
   * @generated
   */
  EAttribute getCARRE_Debut();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.figure.figure.CARRE#getCote <em>Cote</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cote</em>'.
   * @see org.xtext.ipsl.figure.figure.CARRE#getCote()
   * @see #getCARRE()
   * @generated
   */
  EReference getCARRE_Cote();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.figure.figure.CARRE#getRetour <em>Retour</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Retour</em>'.
   * @see org.xtext.ipsl.figure.figure.CARRE#getRetour()
   * @see #getCARRE()
   * @generated
   */
  EReference getCARRE_Retour();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.CARRE#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.xtext.ipsl.figure.figure.CARRE#getEnd()
   * @see #getCARRE()
   * @generated
   */
  EAttribute getCARRE_End();

  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.figure.figure.RECTANGLE <em>RECTANGLE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RECTANGLE</em>'.
   * @see org.xtext.ipsl.figure.figure.RECTANGLE
   * @generated
   */
  EClass getRECTANGLE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see org.xtext.ipsl.figure.figure.RECTANGLE#getNom()
   * @see #getRECTANGLE()
   * @generated
   */
  EAttribute getRECTANGLE_Nom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getDebut <em>Debut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Debut</em>'.
   * @see org.xtext.ipsl.figure.figure.RECTANGLE#getDebut()
   * @see #getRECTANGLE()
   * @generated
   */
  EAttribute getRECTANGLE_Debut();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getLongueur <em>Longueur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Longueur</em>'.
   * @see org.xtext.ipsl.figure.figure.RECTANGLE#getLongueur()
   * @see #getRECTANGLE()
   * @generated
   */
  EReference getRECTANGLE_Longueur();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getLargeur <em>Largeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Largeur</em>'.
   * @see org.xtext.ipsl.figure.figure.RECTANGLE#getLargeur()
   * @see #getRECTANGLE()
   * @generated
   */
  EReference getRECTANGLE_Largeur();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getRetour <em>Retour</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Retour</em>'.
   * @see org.xtext.ipsl.figure.figure.RECTANGLE#getRetour()
   * @see #getRECTANGLE()
   * @generated
   */
  EReference getRECTANGLE_Retour();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.xtext.ipsl.figure.figure.RECTANGLE#getEnd()
   * @see #getRECTANGLE()
   * @generated
   */
  EAttribute getRECTANGLE_End();

  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.figure.figure.CERCLE <em>CERCLE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CERCLE</em>'.
   * @see org.xtext.ipsl.figure.figure.CERCLE
   * @generated
   */
  EClass getCERCLE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.CERCLE#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see org.xtext.ipsl.figure.figure.CERCLE#getNom()
   * @see #getCERCLE()
   * @generated
   */
  EAttribute getCERCLE_Nom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.CERCLE#getDebut <em>Debut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Debut</em>'.
   * @see org.xtext.ipsl.figure.figure.CERCLE#getDebut()
   * @see #getCERCLE()
   * @generated
   */
  EAttribute getCERCLE_Debut();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.figure.figure.CERCLE#getRayon <em>Rayon</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rayon</em>'.
   * @see org.xtext.ipsl.figure.figure.CERCLE#getRayon()
   * @see #getCERCLE()
   * @generated
   */
  EReference getCERCLE_Rayon();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.figure.figure.CERCLE#getRetour <em>Retour</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Retour</em>'.
   * @see org.xtext.ipsl.figure.figure.CERCLE#getRetour()
   * @see #getCERCLE()
   * @generated
   */
  EReference getCERCLE_Retour();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.CERCLE#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.xtext.ipsl.figure.figure.CERCLE#getEnd()
   * @see #getCERCLE()
   * @generated
   */
  EAttribute getCERCLE_End();

  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.figure.figure.RETURN <em>RETURN</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RETURN</em>'.
   * @see org.xtext.ipsl.figure.figure.RETURN
   * @generated
   */
  EClass getRETURN();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.RETURN#getResultat <em>Resultat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Resultat</em>'.
   * @see org.xtext.ipsl.figure.figure.RETURN#getResultat()
   * @see #getRETURN()
   * @generated
   */
  EAttribute getRETURN_Resultat();

  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.figure.figure.REEL <em>REEL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>REEL</em>'.
   * @see org.xtext.ipsl.figure.figure.REEL
   * @generated
   */
  EClass getREEL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.figure.figure.REEL#getReel <em>Reel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reel</em>'.
   * @see org.xtext.ipsl.figure.figure.REEL#getReel()
   * @see #getREEL()
   * @generated
   */
  EAttribute getREEL_Reel();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FigureFactory getFigureFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.ipsl.figure.figure.impl.PROGRAMMEImpl <em>PROGRAMME</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.figure.figure.impl.PROGRAMMEImpl
     * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getPROGRAMME()
     * @generated
     */
    EClass PROGRAMME = eINSTANCE.getPROGRAMME();

    /**
     * The meta object literal for the '<em><b>Fig</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMME__FIG = eINSTANCE.getPROGRAMME_Fig();

    /**
     * The meta object literal for the '{@link org.xtext.ipsl.figure.figure.impl.FIGUREImpl <em>FIGURE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.figure.figure.impl.FIGUREImpl
     * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getFIGURE()
     * @generated
     */
    EClass FIGURE = eINSTANCE.getFIGURE();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIGURE__NOM = eINSTANCE.getFIGURE_Nom();

    /**
     * The meta object literal for the '{@link org.xtext.ipsl.figure.figure.impl.CARREImpl <em>CARRE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.figure.figure.impl.CARREImpl
     * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getCARRE()
     * @generated
     */
    EClass CARRE = eINSTANCE.getCARRE();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARRE__NOM = eINSTANCE.getCARRE_Nom();

    /**
     * The meta object literal for the '<em><b>Debut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARRE__DEBUT = eINSTANCE.getCARRE_Debut();

    /**
     * The meta object literal for the '<em><b>Cote</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARRE__COTE = eINSTANCE.getCARRE_Cote();

    /**
     * The meta object literal for the '<em><b>Retour</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARRE__RETOUR = eINSTANCE.getCARRE_Retour();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARRE__END = eINSTANCE.getCARRE_End();

    /**
     * The meta object literal for the '{@link org.xtext.ipsl.figure.figure.impl.RECTANGLEImpl <em>RECTANGLE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.figure.figure.impl.RECTANGLEImpl
     * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getRECTANGLE()
     * @generated
     */
    EClass RECTANGLE = eINSTANCE.getRECTANGLE();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGLE__NOM = eINSTANCE.getRECTANGLE_Nom();

    /**
     * The meta object literal for the '<em><b>Debut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGLE__DEBUT = eINSTANCE.getRECTANGLE_Debut();

    /**
     * The meta object literal for the '<em><b>Longueur</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECTANGLE__LONGUEUR = eINSTANCE.getRECTANGLE_Longueur();

    /**
     * The meta object literal for the '<em><b>Largeur</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECTANGLE__LARGEUR = eINSTANCE.getRECTANGLE_Largeur();

    /**
     * The meta object literal for the '<em><b>Retour</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECTANGLE__RETOUR = eINSTANCE.getRECTANGLE_Retour();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGLE__END = eINSTANCE.getRECTANGLE_End();

    /**
     * The meta object literal for the '{@link org.xtext.ipsl.figure.figure.impl.CERCLEImpl <em>CERCLE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.figure.figure.impl.CERCLEImpl
     * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getCERCLE()
     * @generated
     */
    EClass CERCLE = eINSTANCE.getCERCLE();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CERCLE__NOM = eINSTANCE.getCERCLE_Nom();

    /**
     * The meta object literal for the '<em><b>Debut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CERCLE__DEBUT = eINSTANCE.getCERCLE_Debut();

    /**
     * The meta object literal for the '<em><b>Rayon</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CERCLE__RAYON = eINSTANCE.getCERCLE_Rayon();

    /**
     * The meta object literal for the '<em><b>Retour</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CERCLE__RETOUR = eINSTANCE.getCERCLE_Retour();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CERCLE__END = eINSTANCE.getCERCLE_End();

    /**
     * The meta object literal for the '{@link org.xtext.ipsl.figure.figure.impl.RETURNImpl <em>RETURN</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.figure.figure.impl.RETURNImpl
     * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getRETURN()
     * @generated
     */
    EClass RETURN = eINSTANCE.getRETURN();

    /**
     * The meta object literal for the '<em><b>Resultat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RETURN__RESULTAT = eINSTANCE.getRETURN_Resultat();

    /**
     * The meta object literal for the '{@link org.xtext.ipsl.figure.figure.impl.REELImpl <em>REEL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.figure.figure.impl.REELImpl
     * @see org.xtext.ipsl.figure.figure.impl.FigurePackageImpl#getREEL()
     * @generated
     */
    EClass REEL = eINSTANCE.getREEL();

    /**
     * The meta object literal for the '<em><b>Reel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REEL__REEL = eINSTANCE.getREEL_Reel();

  }

} //FigurePackage
