/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure.figure;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PROGRAMME</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ipsl.figure.figure.PROGRAMME#getFig <em>Fig</em>}</li>
 * </ul>
 *
 * @see org.xtext.ipsl.figure.figure.FigurePackage#getPROGRAMME()
 * @model
 * @generated
 */
public interface PROGRAMME extends EObject
{
  /**
   * Returns the value of the '<em><b>Fig</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fig</em>' containment reference.
   * @see #setFig(FIGURE)
   * @see org.xtext.ipsl.figure.figure.FigurePackage#getPROGRAMME_Fig()
   * @model containment="true"
   * @generated
   */
  FIGURE getFig();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.figure.figure.PROGRAMME#getFig <em>Fig</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fig</em>' containment reference.
   * @see #getFig()
   * @generated
   */
  void setFig(FIGURE value);

} // PROGRAMME
