/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure.figure;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RECTANGLE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ipsl.figure.figure.RECTANGLE#getNom <em>Nom</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.RECTANGLE#getDebut <em>Debut</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.RECTANGLE#getLongueur <em>Longueur</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.RECTANGLE#getLargeur <em>Largeur</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.RECTANGLE#getRetour <em>Retour</em>}</li>
 *   <li>{@link org.xtext.ipsl.figure.figure.RECTANGLE#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see org.xtext.ipsl.figure.figure.FigurePackage#getRECTANGLE()
 * @model
 * @generated
 */
public interface RECTANGLE extends EObject
{
  /**
   * Returns the value of the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom</em>' attribute.
   * @see #setNom(String)
   * @see org.xtext.ipsl.figure.figure.FigurePackage#getRECTANGLE_Nom()
   * @model
   * @generated
   */
  String getNom();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getNom <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom</em>' attribute.
   * @see #getNom()
   * @generated
   */
  void setNom(String value);

  /**
   * Returns the value of the '<em><b>Debut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Debut</em>' attribute.
   * @see #setDebut(String)
   * @see org.xtext.ipsl.figure.figure.FigurePackage#getRECTANGLE_Debut()
   * @model
   * @generated
   */
  String getDebut();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getDebut <em>Debut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Debut</em>' attribute.
   * @see #getDebut()
   * @generated
   */
  void setDebut(String value);

  /**
   * Returns the value of the '<em><b>Longueur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Longueur</em>' containment reference.
   * @see #setLongueur(REEL)
   * @see org.xtext.ipsl.figure.figure.FigurePackage#getRECTANGLE_Longueur()
   * @model containment="true"
   * @generated
   */
  REEL getLongueur();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getLongueur <em>Longueur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Longueur</em>' containment reference.
   * @see #getLongueur()
   * @generated
   */
  void setLongueur(REEL value);

  /**
   * Returns the value of the '<em><b>Largeur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Largeur</em>' containment reference.
   * @see #setLargeur(REEL)
   * @see org.xtext.ipsl.figure.figure.FigurePackage#getRECTANGLE_Largeur()
   * @model containment="true"
   * @generated
   */
  REEL getLargeur();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getLargeur <em>Largeur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Largeur</em>' containment reference.
   * @see #getLargeur()
   * @generated
   */
  void setLargeur(REEL value);

  /**
   * Returns the value of the '<em><b>Retour</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Retour</em>' containment reference.
   * @see #setRetour(RETURN)
   * @see org.xtext.ipsl.figure.figure.FigurePackage#getRECTANGLE_Retour()
   * @model containment="true"
   * @generated
   */
  RETURN getRetour();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getRetour <em>Retour</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Retour</em>' containment reference.
   * @see #getRetour()
   * @generated
   */
  void setRetour(RETURN value);

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see #setEnd(String)
   * @see org.xtext.ipsl.figure.figure.FigurePackage#getRECTANGLE_End()
   * @model
   * @generated
   */
  String getEnd();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.figure.figure.RECTANGLE#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see #getEnd()
   * @generated
   */
  void setEnd(String value);

} // RECTANGLE
