/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure.figure;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RETURN</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ipsl.figure.figure.RETURN#getResultat <em>Resultat</em>}</li>
 * </ul>
 *
 * @see org.xtext.ipsl.figure.figure.FigurePackage#getRETURN()
 * @model
 * @generated
 */
public interface RETURN extends EObject
{
  /**
   * Returns the value of the '<em><b>Resultat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resultat</em>' attribute.
   * @see #setResultat(String)
   * @see org.xtext.ipsl.figure.figure.FigurePackage#getRETURN_Resultat()
   * @model
   * @generated
   */
  String getResultat();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.figure.figure.RETURN#getResultat <em>Resultat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resultat</em>' attribute.
   * @see #getResultat()
   * @generated
   */
  void setResultat(String value);

} // RETURN
