/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.ipsl.figure.FigureRuntimeModule;
import org.xtext.ipsl.figure.FigureStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FigureIdeSetup extends FigureStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FigureRuntimeModule(), new FigureIdeModule()));
	}
	
}
