/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.mydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MonDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/ipsl/mydsl/parser/antlr/internal/InternalMonDsl.tokens");
	}
}
