/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.ipsl.mydsl.parser.antlr.internal.InternalMonDslParser;
import org.xtext.ipsl.mydsl.services.MonDslGrammarAccess;

public class MonDslParser extends AbstractAntlrParser {

	@Inject
	private MonDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMonDslParser createParser(XtextTokenStream stream) {
		return new InternalMonDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MonDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MonDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
