/**
 * generated by Xtext 2.29.0
 */
package org.xtext.ipsl.calcul.calcul;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.ipsl.calcul.calcul.CalculFactory
 * @model kind="package"
 * @generated
 */
public interface CalculPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "calcul";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/ipsl/calcul/Calcul";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "calcul";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CalculPackage eINSTANCE = org.xtext.ipsl.calcul.calcul.impl.CalculPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.ipsl.calcul.calcul.impl.CALCULImpl <em>CALCUL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.calcul.calcul.impl.CALCULImpl
   * @see org.xtext.ipsl.calcul.calcul.impl.CalculPackageImpl#getCALCUL()
   * @generated
   */
  int CALCUL = 0;

  /**
   * The feature id for the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALCUL__OPERATION = 0;

  /**
   * The number of structural features of the '<em>CALCUL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALCUL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ipsl.calcul.calcul.impl.STATISTIQUEImpl <em>STATISTIQUE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.calcul.calcul.impl.STATISTIQUEImpl
   * @see org.xtext.ipsl.calcul.calcul.impl.CalculPackageImpl#getSTATISTIQUE()
   * @generated
   */
  int STATISTIQUE = 1;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTIQUE__NOM = 0;

  /**
   * The feature id for the '<em><b>Debut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTIQUE__DEBUT = 1;

  /**
   * The feature id for the '<em><b>Modalite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTIQUE__MODALITE = 2;

  /**
   * The feature id for the '<em><b>Effectif</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTIQUE__EFFECTIF = 3;

  /**
   * The feature id for the '<em><b>Resultat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTIQUE__RESULTAT = 4;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTIQUE__END = 5;

  /**
   * The number of structural features of the '<em>STATISTIQUE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTIQUE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.ipsl.calcul.calcul.impl.MODALITEImpl <em>MODALITE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.calcul.calcul.impl.MODALITEImpl
   * @see org.xtext.ipsl.calcul.calcul.impl.CalculPackageImpl#getMODALITE()
   * @generated
   */
  int MODALITE = 2;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODALITE__VALUES = 0;

  /**
   * The number of structural features of the '<em>MODALITE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODALITE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ipsl.calcul.calcul.impl.EFFECTIFImpl <em>EFFECTIF</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ipsl.calcul.calcul.impl.EFFECTIFImpl
   * @see org.xtext.ipsl.calcul.calcul.impl.CalculPackageImpl#getEFFECTIF()
   * @generated
   */
  int EFFECTIF = 3;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EFFECTIF__VALUES = 0;

  /**
   * The number of structural features of the '<em>EFFECTIF</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EFFECTIF_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.calcul.calcul.CALCUL <em>CALCUL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CALCUL</em>'.
   * @see org.xtext.ipsl.calcul.calcul.CALCUL
   * @generated
   */
  EClass getCALCUL();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.calcul.calcul.CALCUL#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operation</em>'.
   * @see org.xtext.ipsl.calcul.calcul.CALCUL#getOperation()
   * @see #getCALCUL()
   * @generated
   */
  EReference getCALCUL_Operation();

  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE <em>STATISTIQUE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>STATISTIQUE</em>'.
   * @see org.xtext.ipsl.calcul.calcul.STATISTIQUE
   * @generated
   */
  EClass getSTATISTIQUE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see org.xtext.ipsl.calcul.calcul.STATISTIQUE#getNom()
   * @see #getSTATISTIQUE()
   * @generated
   */
  EAttribute getSTATISTIQUE_Nom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getDebut <em>Debut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Debut</em>'.
   * @see org.xtext.ipsl.calcul.calcul.STATISTIQUE#getDebut()
   * @see #getSTATISTIQUE()
   * @generated
   */
  EAttribute getSTATISTIQUE_Debut();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getModalite <em>Modalite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Modalite</em>'.
   * @see org.xtext.ipsl.calcul.calcul.STATISTIQUE#getModalite()
   * @see #getSTATISTIQUE()
   * @generated
   */
  EReference getSTATISTIQUE_Modalite();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getEffectif <em>Effectif</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Effectif</em>'.
   * @see org.xtext.ipsl.calcul.calcul.STATISTIQUE#getEffectif()
   * @see #getSTATISTIQUE()
   * @generated
   */
  EReference getSTATISTIQUE_Effectif();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getResultat <em>Resultat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Resultat</em>'.
   * @see org.xtext.ipsl.calcul.calcul.STATISTIQUE#getResultat()
   * @see #getSTATISTIQUE()
   * @generated
   */
  EAttribute getSTATISTIQUE_Resultat();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.xtext.ipsl.calcul.calcul.STATISTIQUE#getEnd()
   * @see #getSTATISTIQUE()
   * @generated
   */
  EAttribute getSTATISTIQUE_End();

  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.calcul.calcul.MODALITE <em>MODALITE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MODALITE</em>'.
   * @see org.xtext.ipsl.calcul.calcul.MODALITE
   * @generated
   */
  EClass getMODALITE();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.ipsl.calcul.calcul.MODALITE#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see org.xtext.ipsl.calcul.calcul.MODALITE#getValues()
   * @see #getMODALITE()
   * @generated
   */
  EAttribute getMODALITE_Values();

  /**
   * Returns the meta object for class '{@link org.xtext.ipsl.calcul.calcul.EFFECTIF <em>EFFECTIF</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EFFECTIF</em>'.
   * @see org.xtext.ipsl.calcul.calcul.EFFECTIF
   * @generated
   */
  EClass getEFFECTIF();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.ipsl.calcul.calcul.EFFECTIF#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see org.xtext.ipsl.calcul.calcul.EFFECTIF#getValues()
   * @see #getEFFECTIF()
   * @generated
   */
  EAttribute getEFFECTIF_Values();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CalculFactory getCalculFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.ipsl.calcul.calcul.impl.CALCULImpl <em>CALCUL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.calcul.calcul.impl.CALCULImpl
     * @see org.xtext.ipsl.calcul.calcul.impl.CalculPackageImpl#getCALCUL()
     * @generated
     */
    EClass CALCUL = eINSTANCE.getCALCUL();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALCUL__OPERATION = eINSTANCE.getCALCUL_Operation();

    /**
     * The meta object literal for the '{@link org.xtext.ipsl.calcul.calcul.impl.STATISTIQUEImpl <em>STATISTIQUE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.calcul.calcul.impl.STATISTIQUEImpl
     * @see org.xtext.ipsl.calcul.calcul.impl.CalculPackageImpl#getSTATISTIQUE()
     * @generated
     */
    EClass STATISTIQUE = eINSTANCE.getSTATISTIQUE();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATISTIQUE__NOM = eINSTANCE.getSTATISTIQUE_Nom();

    /**
     * The meta object literal for the '<em><b>Debut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATISTIQUE__DEBUT = eINSTANCE.getSTATISTIQUE_Debut();

    /**
     * The meta object literal for the '<em><b>Modalite</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATISTIQUE__MODALITE = eINSTANCE.getSTATISTIQUE_Modalite();

    /**
     * The meta object literal for the '<em><b>Effectif</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATISTIQUE__EFFECTIF = eINSTANCE.getSTATISTIQUE_Effectif();

    /**
     * The meta object literal for the '<em><b>Resultat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATISTIQUE__RESULTAT = eINSTANCE.getSTATISTIQUE_Resultat();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATISTIQUE__END = eINSTANCE.getSTATISTIQUE_End();

    /**
     * The meta object literal for the '{@link org.xtext.ipsl.calcul.calcul.impl.MODALITEImpl <em>MODALITE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.calcul.calcul.impl.MODALITEImpl
     * @see org.xtext.ipsl.calcul.calcul.impl.CalculPackageImpl#getMODALITE()
     * @generated
     */
    EClass MODALITE = eINSTANCE.getMODALITE();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODALITE__VALUES = eINSTANCE.getMODALITE_Values();

    /**
     * The meta object literal for the '{@link org.xtext.ipsl.calcul.calcul.impl.EFFECTIFImpl <em>EFFECTIF</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ipsl.calcul.calcul.impl.EFFECTIFImpl
     * @see org.xtext.ipsl.calcul.calcul.impl.CalculPackageImpl#getEFFECTIF()
     * @generated
     */
    EClass EFFECTIF = eINSTANCE.getEFFECTIF();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EFFECTIF__VALUES = eINSTANCE.getEFFECTIF_Values();

  }

} //CalculPackage
