/**
 * generated by Xtext 2.29.0
 */
package org.xtext.ipsl.calcul.calcul;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CALCUL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ipsl.calcul.calcul.CALCUL#getOperation <em>Operation</em>}</li>
 * </ul>
 *
 * @see org.xtext.ipsl.calcul.calcul.CalculPackage#getCALCUL()
 * @model
 * @generated
 */
public interface CALCUL extends EObject
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' containment reference.
   * @see #setOperation(STATISTIQUE)
   * @see org.xtext.ipsl.calcul.calcul.CalculPackage#getCALCUL_Operation()
   * @model containment="true"
   * @generated
   */
  STATISTIQUE getOperation();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.calcul.calcul.CALCUL#getOperation <em>Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' containment reference.
   * @see #getOperation()
   * @generated
   */
  void setOperation(STATISTIQUE value);

} // CALCUL
