/**
 * generated by Xtext 2.29.0
 */
package org.xtext.ipsl.calcul.calcul;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>STATISTIQUE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getNom <em>Nom</em>}</li>
 *   <li>{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getDebut <em>Debut</em>}</li>
 *   <li>{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getModalite <em>Modalite</em>}</li>
 *   <li>{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getEffectif <em>Effectif</em>}</li>
 *   <li>{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getResultat <em>Resultat</em>}</li>
 *   <li>{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see org.xtext.ipsl.calcul.calcul.CalculPackage#getSTATISTIQUE()
 * @model
 * @generated
 */
public interface STATISTIQUE extends EObject
{
  /**
   * Returns the value of the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom</em>' attribute.
   * @see #setNom(String)
   * @see org.xtext.ipsl.calcul.calcul.CalculPackage#getSTATISTIQUE_Nom()
   * @model
   * @generated
   */
  String getNom();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getNom <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom</em>' attribute.
   * @see #getNom()
   * @generated
   */
  void setNom(String value);

  /**
   * Returns the value of the '<em><b>Debut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Debut</em>' attribute.
   * @see #setDebut(String)
   * @see org.xtext.ipsl.calcul.calcul.CalculPackage#getSTATISTIQUE_Debut()
   * @model
   * @generated
   */
  String getDebut();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getDebut <em>Debut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Debut</em>' attribute.
   * @see #getDebut()
   * @generated
   */
  void setDebut(String value);

  /**
   * Returns the value of the '<em><b>Modalite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modalite</em>' containment reference.
   * @see #setModalite(MODALITE)
   * @see org.xtext.ipsl.calcul.calcul.CalculPackage#getSTATISTIQUE_Modalite()
   * @model containment="true"
   * @generated
   */
  MODALITE getModalite();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getModalite <em>Modalite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modalite</em>' containment reference.
   * @see #getModalite()
   * @generated
   */
  void setModalite(MODALITE value);

  /**
   * Returns the value of the '<em><b>Effectif</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Effectif</em>' containment reference.
   * @see #setEffectif(EFFECTIF)
   * @see org.xtext.ipsl.calcul.calcul.CalculPackage#getSTATISTIQUE_Effectif()
   * @model containment="true"
   * @generated
   */
  EFFECTIF getEffectif();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getEffectif <em>Effectif</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Effectif</em>' containment reference.
   * @see #getEffectif()
   * @generated
   */
  void setEffectif(EFFECTIF value);

  /**
   * Returns the value of the '<em><b>Resultat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resultat</em>' attribute.
   * @see #setResultat(String)
   * @see org.xtext.ipsl.calcul.calcul.CalculPackage#getSTATISTIQUE_Resultat()
   * @model
   * @generated
   */
  String getResultat();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getResultat <em>Resultat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resultat</em>' attribute.
   * @see #getResultat()
   * @generated
   */
  void setResultat(String value);

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see #setEnd(String)
   * @see org.xtext.ipsl.calcul.calcul.CalculPackage#getSTATISTIQUE_End()
   * @model
   * @generated
   */
  String getEnd();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.calcul.calcul.STATISTIQUE#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see #getEnd()
   * @generated
   */
  void setEnd(String value);

} // STATISTIQUE
