/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.ipsl.mondsl.ui.internal.MondslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MonDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MondslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MondslActivator activator = MondslActivator.getInstance();
		return activator != null ? activator.getInjector(MondslActivator.ORG_XTEXT_IPSL_MYDSL_MONDSL) : null;
	}

}
