/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.airport;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AirPortStandaloneSetup extends AirPortStandaloneSetupGenerated {

	public static void doSetup() {
		new AirPortStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
