/*
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.figure;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FigureStandaloneSetup extends FigureStandaloneSetupGenerated {

	public static void doSetup() {
		new FigureStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
