/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.airport.airPort;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aeroport</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ipsl.airport.airPort.Aeroport#getNom <em>Nom</em>}</li>
 *   <li>{@link org.xtext.ipsl.airport.airPort.Aeroport#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.ipsl.airport.airPort.Aeroport#getPays <em>Pays</em>}</li>
 *   <li>{@link org.xtext.ipsl.airport.airPort.Aeroport#getPistes <em>Pistes</em>}</li>
 * </ul>
 *
 * @see org.xtext.ipsl.airport.airPort.AirPortPackage#getAeroport()
 * @model
 * @generated
 */
public interface Aeroport extends EObject
{
  /**
   * Returns the value of the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom</em>' attribute.
   * @see #setNom(String)
   * @see org.xtext.ipsl.airport.airPort.AirPortPackage#getAeroport_Nom()
   * @model
   * @generated
   */
  String getNom();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.airport.airPort.Aeroport#getNom <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom</em>' attribute.
   * @see #getNom()
   * @generated
   */
  void setNom(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(CodeOACI)
   * @see org.xtext.ipsl.airport.airPort.AirPortPackage#getAeroport_Name()
   * @model containment="true"
   * @generated
   */
  CodeOACI getName();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.airport.airPort.Aeroport#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(CodeOACI value);

  /**
   * Returns the value of the '<em><b>Pays</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pays</em>' attribute.
   * @see #setPays(String)
   * @see org.xtext.ipsl.airport.airPort.AirPortPackage#getAeroport_Pays()
   * @model
   * @generated
   */
  String getPays();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.airport.airPort.Aeroport#getPays <em>Pays</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pays</em>' attribute.
   * @see #getPays()
   * @generated
   */
  void setPays(String value);

  /**
   * Returns the value of the '<em><b>Pistes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pistes</em>' attribute.
   * @see #setPistes(int)
   * @see org.xtext.ipsl.airport.airPort.AirPortPackage#getAeroport_Pistes()
   * @model
   * @generated
   */
  int getPistes();

  /**
   * Sets the value of the '{@link org.xtext.ipsl.airport.airPort.Aeroport#getPistes <em>Pistes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pistes</em>' attribute.
   * @see #getPistes()
   * @generated
   */
  void setPistes(int value);

} // Aeroport
