/**
 * generated by Xtext 2.30.0
 */
package org.xtext.ipsl.airport.airPort;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.ipsl.airport.airPort.AirPortPackage
 * @generated
 */
public interface AirPortFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AirPortFactory eINSTANCE = org.xtext.ipsl.airport.airPort.impl.AirPortFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Avion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Avion</em>'.
   * @generated
   */
  Avion createAvion();

  /**
   * Returns a new object of class '<em>Aeroport</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Aeroport</em>'.
   * @generated
   */
  Aeroport createAeroport();

  /**
   * Returns a new object of class '<em>Ligne</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ligne</em>'.
   * @generated
   */
  Ligne createLigne();

  /**
   * Returns a new object of class '<em>Code OACI</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Code OACI</em>'.
   * @generated
   */
  CodeOACI createCodeOACI();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AirPortPackage getAirPortPackage();

} //AirPortFactory
