/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mondsl1.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mondsl1.MyDsl1RuntimeModule;
import org.xtext.example.mondsl1.MyDsl1StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDsl1IdeSetup extends MyDsl1StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDsl1RuntimeModule(), new MyDsl1IdeModule()));
	}
	
}
