/*
 * generated by Xtext 2.29.0
 */
package org.xtext.ipsl.calcul.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCalculValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.ipsl.calcul.calcul.CalculPackage.eINSTANCE);
		return result;
	}
}
